import { ImageSourcePropType } from 'react-native';

const DICEBEAR_STYLE = 'fun-emoji';

// Builds the image source for an avatar from its raw parts. If an uploaded
// avatar URL exists, it is used. Otherwise a deterministic placeholder is
// generated by DiceBear from the username as seed, so every user gets a stable,
// unique image even without an uploaded picture.
export function getAvatarSourceFromParts(username: string, avatarUrl: string | null): ImageSourcePropType {
  if (avatarUrl) return { uri: avatarUrl };

  const seed = encodeURIComponent(username);
  return { uri: `https://api.dicebear.com/9.x/${DICEBEAR_STYLE}/png?seed=${seed}` };
}

// Convenience wrapper for the (legacy, snake_case) Profile type.
export default function getAvatarSource(profile: Profile): ImageSourcePropType {
  return getAvatarSourceFromParts(profile.username, profile.avatar_url);
}
